"""
System Tool.
Handles file operations and system commands.

!!! WARNING !!!
This module has access to the operating system.
ALL text generated by the LLM must be strictly sanitized.
Risk of data loss or security breach if not handled carefully.
"""

import os
from jarvis_ai.core.safety import SafetyManager

class SystemTool:
    def __init__(self, execution_mode='mock'):
        self.execution_mode = execution_mode
        self.safety = SafetyManager()

    def set_mode(self, mode):
        self.execution_mode = mode

    def create_file(self, filename):
        """
        Create a new file.
        """
        if self.execution_mode == 'real':
            if self.safety.ask_confirmation(f"Create file '{filename}'"):
                try:
                    with open(filename, 'w') as f:
                        f.write("") # Create empty
                    return f"File '{filename}' created successfully (REAL)."
                except Exception as e:
                    return f"Error creating file: {e}"
            return "Action cancelled by user."
        
        # Mock
        print(f"[SYSTEM] Creating file: {filename}")
        return f"File '{filename}' created successfully (MOCK)."

    def write_file(self, filename, content):
        """
        Write content to a file.
        """
        if self.execution_mode == 'real':
             if self.safety.ask_confirmation(f"Write to file '{filename}'"):
                try:
                    with open(filename, 'w') as f:
                        f.write(content)
                    return f"Content written to '{filename}' successfully (REAL)."
                except Exception as e:
                    return f"Error writing file: {e}"
             return "Action cancelled by user."

        # Mock implementation
        print(f"[SYSTEM] Writing to file: {filename}")
        print(f"[SYSTEM] Content preview: {content[:50]}...")
        return f"Content written to '{filename}' successfully (MOCK)."

    def run_command(self, command):
        """
        Execute a shell command.
        """
        if self.execution_mode == 'real':
             if self.safety.ask_confirmation(f"Run shell command: '{command}'"):
                # Warning: os.system is simple but capture output is harder. 
                # using subprocess would be better but keeping it simple for now.
                exit_code = os.system(command)
                return f"Command executed with exit code {exit_code} (REAL)."
             return "Action cancelled by user."

        # Mock implementation
        print(f"[SYSTEM] Executing command: {command}")
        return f"Command '{command}' executed (MOCK)."
